### PR TITLE
Fix check for existing reporting file to append the EDGE-T reporting

### PR DESCRIPTION
**Pull request by Loisel**
(hopefully) addresses issue #245

### CODE REVIEW

**Review by orichters — APPROVED** [review]
Thanks, @loisel, I tested it with both existing adjustPolicyCost runs and without and it solves the issue!

Did you delete the `miffile <- readMIF(name_mif)` on purpose? It seems not to be used later anyway.

On the other hand, if you just add further .mif files for whatever reasons into your output folder, it may break again. An alternative I think would be to add the option `file = NULL` to the function definition, do the search only if no such file is provided, and add `file = remind_reporting_file` [here](https://github.com/remindmodel/remind/blob/develop/scripts/output/single/reporting.R#L63).

But anyway, it fixes the problem that I had, and thanks a lot for your quick reaction!

**Comment by Loisel** [comment]
Yes, that is a good idea! I thought about passing a parameter but decided to not break the interface. But having it optional would certainly do the trick! I consider returning the data (instead of appending) even more elegant. Maybe I would add a parameter `append=TRUE` which will search and append to mif for backwards compatibility but in the REMIND reporting script append the data explicitly.

**Comment by Loisel** [comment]
> Did you delete the `miffile <- readMIF(name_mif)` on purpose? It seems not to be used later anyway.

Indeed, this line was an artifact.

**Comment by orichters** [comment]
Looks good. So you plan to change [reporting.R](https://github.com/remindmodel/remind/blob/develop/scripts/output/single/reporting.R) in REMIND as well? Although I see it is not strictly necessary…

**Review by orichters — APPROVED** [review]

**Comment by Loisel** [comment]
> Looks good. So you plan to change [reporting.R](https://github.com/remindmodel/remind/blob/develop/scripts/output/single/reporting.R) in REMIND as well? Although I see it is not strictly necessary…

Yes, I'll provide a PR as soon as the change hits master. The newer version of the EDGE-T reporting will return a quitte object, so this change in a sense is an acceptance test.

**Review by MariannaR — APPROVED** [review]

**Comment by Loisel** [comment]
> Looks good. So you plan to change [reporting.R](https://github.com/remindmodel/remind/blob/develop/scripts/output/single/reporting.R) in REMIND as well? Although I see it is not strictly necessary…

Yes, I'll provide a PR as soon as the change hits master. The newer version of the EDGE-T reporting will return a quitte object, so this change in a sense is an acceptance test.

**Pull request merged**
