### PR TITLE
new carbon management section in cs2

### PR DESCRIPTION
**Pull request by chroetz**
There is a new section "Carbon Management" in `compareScenarios2()`. It contains plots of all variables which start with "Carbon Management".

### CODE REVIEW

**Comment by chroetz** [comment]
Example: [cs2_SDP-AMT_09_carbon_management.pdf](https://github.com/pik-piam/remind2/files/7883868/cs2_SDP-AMT_09_carbon_management.pdf)

**Comment by fschreyer** [comment]
Hi Christof, 

thanks for this! Looks very good.

Two points:

* I would shorten the y-axes labels which are sometimes hard to read. What about taking the short version of the variable name (which you currently have as the title) like "Storage" as the y label and take the long version "Carbon Management|Carbon Sinks|Storage" as the title?

* ``Carbon Management|Share of Stored CO2 from Captured`` should not be summed up over all regions to get the global value, I just realized. Rather, it should be the aggregation weighted by captured CO2. We will need to add that in the emissions reporting similar to what we have in the price reporting [here](https://github.com/pik-piam/remind2/blob/2d9b5cd93c3b7b27779999cd71c909e7e1eb66d2/R/reportPrices.R#L420). Not necessary for now, just to keep in mind for later. 

PS: Btw, regarding your pdf, I am not sure anymore about our policy of showing model output publicly on github. Personally, I don't find this problematic, but I remember we had a group discussion about it. Perhaps, it would be good to bring this up in the remind meeting once more.

**Review by amerfort — APPROVED** [review]
Looks good to me. Very helpful, thanks!

**Comment by chroetz** [comment]
Thank you all for the helpful comments. 

* First a comment on the choice of variables in the plots:
The plots are created mechanically, so to speak: I looked at the list of all available "Carbon Management"-variables:
```
 [1] "Carbon Management|Carbon Capture"                                           
 [2] "Carbon Management|Carbon Sinks"                                             
 [3] "Carbon Management|Carbon Sinks|+|CCU"                                       
 [4] "Carbon Management|Carbon Sinks|+|Storage"                                   
 [5] "Carbon Management|Carbon Sinks|CCU|+|Synthetic Gases"                       
 [6] "Carbon Management|Carbon Sinks|CCU|+|Synthetic Liquids"                     
 [7] "Carbon Management|Carbon Sinks|Storage|+|Biomass|Pe2Se"                     
 [8] "Carbon Management|Carbon Sinks|Storage|+|DAC"                               
 [9] "Carbon Management|Carbon Sinks|Storage|+|EW"                                
[10] "Carbon Management|Carbon Sinks|Storage|+|Fossil|Pe2Se"                      
[11] "Carbon Management|Carbon Sinks|Storage|+|Industry Energy"                   
[12] "Carbon Management|Carbon Sinks|Storage|+|Industry Process"                  
[13] "Carbon Management|Carbon Sinks|Storage|Industry Energy|+|Biomass"           
[14] "Carbon Management|Carbon Sinks|Storage|Industry Energy|+|Fossil"            
[15] "Carbon Management|Carbon Sinks|Storage|Industry Energy|+|Synfuel"           
[16] "Carbon Management|Carbon Sources"                                           
[17] "Carbon Management|Carbon Sources|+|Biomass|Pe2Se"                           
[18] "Carbon Management|Carbon Sources|+|DAC"                                     
[19] "Carbon Management|Carbon Sources|+|EW"                                      
[20] "Carbon Management|Carbon Sources|+|Fossil|Pe2Se"                            
[21] "Carbon Management|Carbon Sources|+|Industry Energy"                         
[22] "Carbon Management|Carbon Sources|+|Industry Process"                        
[23] "Carbon Management|Carbon Sources|Biomass|Pe2Se|+|Electricity w/ couple prod"
[24] "Carbon Management|Carbon Sources|Biomass|Pe2Se|+|Gases w/ couple prod"      
[25] "Carbon Management|Carbon Sources|Biomass|Pe2Se|+|Heat w/ couple prod"       
[26] "Carbon Management|Carbon Sources|Biomass|Pe2Se|+|Hydrogen w/ couple prod"   
[27] "Carbon Management|Carbon Sources|Biomass|Pe2Se|+|Liquids w/ couple prod"    
[28] "Carbon Management|Carbon Sources|Biomass|Pe2Se|+|Solids w/ couple prod"     
[29] "Carbon Management|Carbon Sources|Fossil|Pe2Se|+|Electricity w/ couple prod" 
[30] "Carbon Management|Carbon Sources|Fossil|Pe2Se|+|Gases w/ couple prod"       
[31] "Carbon Management|Carbon Sources|Fossil|Pe2Se|+|Heat w/ couple prod"        
[32] "Carbon Management|Carbon Sources|Fossil|Pe2Se|+|Hydrogen w/ couple prod"    
[33] "Carbon Management|Carbon Sources|Fossil|Pe2Se|+|Liquids w/ couple prod"     
[34] "Carbon Management|Carbon Sources|Fossil|Pe2Se|+|Solids w/ couple prod"      
[35] "Carbon Management|Carbon Sources|Industry Energy|+|Biomass"                 
[36] "Carbon Management|Carbon Sources|Industry Energy|+|Fossil"                  
[37] "Carbon Management|Carbon Sources|Industry Energy|+|Synfuel"                 
[38] "Carbon Management|Share of Stored CO2 from Captured CO2" 
```
Then I created a the default area and bar plots for each group of variables that sums to a different variable as indicated by the `|+|`-notation. Additionally there are the 3 line plots for the 3 root variables, i.e., the variables that are not aggregated to a variable.
* I agree that the y-labels are too long. The advantage of showing the whole first part of the variable names shown is that you don't need to know in which section you are to understand which variables are plotted. I will think about a solution.
* I removed the PDF and can send it to you later.
* About `Carbon Management|Share of Stored CO2 from Captured`: Yes, a share of 1200% is a little odd... ;)
* On the first 3 points of @strefler : I do not yet know the reporting and the interpretation of the variables. Maybe we can have a zoom together with @fschreyer 
* Area plots disaggregated by region are not standard in compareScenarios2 yet. But I like the idea and will implement it :)

**Pull request closed without merging**
