### PR TITLE
Automated integrity tests based on the existence of plus (+) symbols …

### PR DESCRIPTION
**Pull request by giannou**
…in the variable names

### CODE REVIEW

**Comment by giannou** [comment]
Here's my proposal for the integrity checks based on the pluses in the variable names. While implementing I came across an issue: https://github.com/pik-piam/remind2/issues/3, and identified 2 cases (out of ~80, not bad!) where totals don't add up:
`FE|Transport|Pass|+|Electricity` and `FE|Gases|+|Fossil`. 

The whole thing will be ready to be added to the package once this PR has been processed: https://github.com/pik-piam/mip/pull/16

**Comment by Renato-Rodrigues** [comment]
Could you be more specific on the sums that are having problems so I can fix them?

ex: for FE|Gases|+|Fossil, the error is because FE|Gases is not being summed up correctly, or is it because "FE|Gases|Fossil|+|Natural Gas (EJ/yr)" + "FE|Gases|Fossil|+|Coal (EJ/yr)" are not summing up to FE|Gases|+|Fossil?

**Comment by Renato-Rodrigues** [comment]
I removed for now the plus signs of the children variables for these variables as indeed they do not sum to the parent.

**Comment by giannou** [comment]
There is another category of potential mistake: these variables are missing as totals (i.e. their children variables exist but there is no total to add up to): `FE|Transport|Pass|ESD`, `FE|Transport|Pass|other`, `FE|Transport|Pass|w/o Bunkers`, `FE|Transport|Freight|w/o Bunkers`, `FE|Transport|Freight|Bunkers`

**Comment by giannou** [comment]
@Renato-Rodrigues how do you suggest to proceed with the missing totals? see last comment

**Comment by Renato-Rodrigues** [comment]
@giannou, sorry, I couldn't take a look at them yet. 
I will take care of them either by including the missing totals or removing the signs in the next days.

**Comment by giannou** [comment]
@Loisel uncommenting the line with `success` did not work for me, I get an error `function 'success' not found`. Any idea why?

**Comment by Loisel** [comment]
yeah sorry it has to be `succeed()`, see https://www.rdocumentation.org/packages/testthat/versions/3.0.1/topics/fail

**Pull request merged**
