### PR TITLE
Add reporting of rocks for enhanced weathering and plots to cs2

### PR DESCRIPTION
**Pull request by tabeado**
This PR adds **reporting** of rock variables for enhanced weathering: 
a) the amount of rocks spread in each time step: v33_EW_onfield
b) the amount of rocks weathering on the field (accumulating over time): v33_EW_onfield_tot
For each, the total and amounts by climate grade (warm and temperate regions) are included.

It further adds **2 lineplots to cs2**, showing only the total of spreading and of weathering on the fields.
The plots are added to the CDR emissions section (chapter 2) where otherwise only GHG emissions are shown.
There are no other CDR-specific reportings, thus it does not yet justify the addition of another chapter.

It is currently not backwards compatible with REMIND versions prior to the CDR module refactoring.

### CODE REVIEW

**Comment by tabeado** [comment]
@LaviniaBaumstark  I do not understand why the check is failing, could you help me out please?

**Comment by tabeado** [comment]
@fbenke-pik  or @LaviniaBaumstark, would one of you have time to briefly review this PR, or could you recommend someone else to do it? Many thanks!

**Comment by fbenke-pik** [comment]
Looks good to me. Just resolve the conflicts with buildLibrary, then I will approve

**Comment by tabeado** [comment]
Many thanks @fbenke-pik !

**Review by fbenke-pik — APPROVED** [review]

**Pull request merged**
