### PR TITLE
Adjust LCOE reporting to renamed variable vm_costInvTeAdj

### PR DESCRIPTION
**Pull request by JakobBD**
Minor bugfix to adjust LCOE reporting to [this ](https://github.com/remindmodel/remind/commit/17e8afcb3abd808f2a13e2cddfe08d619481f306) commit changing [this ](https://github.com/remindmodel/remind/blob/6e1243f3e8920d374e95b1a8c6edddeb7fe03e3e/core/declarations.gms#L345) variable name from `v_costInvTeAdj` to `vm_costInvTeAdj`.

### CODE REVIEW

**Comment by fbenke-pik** [comment]
Shouldn't @sophiefuchs be the reviewer for this one?

**Comment by tabeado** [comment]
As far as I can see, not only v_costInvTeAdj but also v_costInvTeDir were changed in the Remind commit. Thus maybe also update the name v_costInvTeDir to vm_costInvTeDir?

**Comment by JakobBD** [comment]
The new name was somehow already present in the readGDX command, so that it didn't cause errors, but now I changed the R variable name as well.

**Comment by tabeado** [comment]
great, thank you!

**Review by tabeado — APPROVED** [review]

**Pull request merged**
