### PR TITLE
add additional summation checks

### PR DESCRIPTION
**Pull request by fbenke-pik**

### CODE REVIEW

**Comment by fbenke-pik** [comment]
Currently, significant gaps for these additional summation checks make the convGDX2MIF test fail. Affected summations are `FE|Industry|Steel|++|Primary`, `Emi|GHG`, `Emi|GHG 1`, `SE|Electricity`, `SE|Hydrogen`, `Carbon Management|Carbon Capture`

**Comment by fbenke-pik** [comment]
@0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q if you send me an updated gdx for testing, i can replace it and check, which of the errors remain.

**Comment by fbenke-pik** [comment]
> Is it expected that these summation checks still fail? If so, how should we go about this: ignore warning or fix them before merging this?

For this specific case, all the failures were for checks added manually via summations file. So the most straightforward options to react are: fixing the failed checks or fixing/removing the check from the summations file.

**Comment by fbenke-pik** [comment]
Ok, i replaced the gdx used for testing and the `FE|Industry|Steel|++|Primary` check no longer fails.

**Comment by fbenke-pik** [comment]
@fschreyer Gaps with an up-to-date gdx

``
### Analyzing provided data.
# Use ~/dev/pik-piam/remind2/inst/extdata/additional_summation_checks.csv to check if summation groups add up.
# Analyzing results of model REMIND

variable groups found in additional_summation_checks.csv                      

Carbon Management|Carbon Capture >                                            
   + Carbon Management|Storage                                             
   + Carbon Management|Usage                                               
Relative difference between 1.08% and 100%, absolute difference up to 300.02 Mt CO2/yr.

Emi|GHG <>                                                                    
   + Emi|GHG|Gross|Energy|Supply|Electricity                               
   + Emi|GHG|Gross|Energy|Supply|Non-electric                              
   + Emi|GHG|Energy|Demand|+|Buildings                                     
   + Emi|GHG|Gross|Energy|Demand|+|Industry                                
   + Emi|GHG|Energy|Demand|+|Transport                                     
   + Emi|GHG|Energy|Demand|+|CDR                                           
   + Emi|GHG|+++|Industrial Processes                                      
   + Emi|GHG|+++|Waste                                                     
   + Emi|GHG|+++|Agriculture                                               
   + Emi|GHG|+++|Land-Use Change                                           
   + Emi|CO2|CDR|BECCS                                                     
   + Emi|CO2|CDR|DACCS                                                     
   + Emi|CO2|CDR|Industry CCS|Synthetic Fuels                              
   + Emi|CO2|CDR|EW                                                        
   + Emi|CO2|+|Energy                                                      
Relative difference between -92.97% and 7.4%, absolute difference up to 39769.51 Mt CO2eq/yr.

Emi|GHG 1 <>                                                                  
   + Emi|CO2|+|Industrial Processes                                        
   + Emi|CO2|+|Land-Use Change                                             
   + Emi|GHG|+|CH4                                                         
   + Emi|GHG|+|N2O                                                         
   + Emi|GHG|+|F-Gases                                                     
   + Emi|CO2|+|non-BECCS CDR                                               
Relative difference between -7.4% and 92.97%, absolute difference up to 39769.51 Mt CO2eq/yr.

SE|Electricity >                                                              
   + SE|Input|Electricity|Hydrogen|Synthetic Fuels|+|Liquids               
   + SE|Input|Electricity|Hydrogen|Synthetic Fuels|+|Gases                 
   + SE|Input|Electricity|Hydrogen|direct FE H2                            
   + SE|Input|Electricity|Hydrogen|Electricity Storage                     
   + SE|Input|Electricity|Buildings                                        
   + SE|Input|Electricity|Industry                                         
   + SE|Input|Electricity|Transport                                        
   + SE|Input|Electricity|CDR                                              
   + SE|Input|Electricity|Self Consumption Energy System                   
Relative difference between 0.000136% and 6.5%, absolute difference up to 1.3 EJ/yr.

SE|Hydrogen >                                                                 
   + FE|Industry|+|Hydrogen                                                
   + FE|Buildings|+|Hydrogen                                               
   + FE|Transport|+|Hydrogen                                               
   + FE|CDR|+|Hydrogen                                                     
   + SE|Input|Hydrogen|Electricity|+|Normal Turbines                       
   + SE|Input|Hydrogen|Electricity|+|Forced VRE Turbines                   
   + SE|Input|Hydrogen|Synthetic Fuels|+|Liquids                           
   + SE|Input|Hydrogen|Synthetic Fuels|+|Gases                             
Relative difference between 0.123% and 81.11%, absolute difference up to 0.0316 EJ/yr.
```

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> Gaps with an up-to-date gdx

Excellent!
Now we know more about the quality of our post-processing.
Commit these additional checks, update the gdxes `test-convGDX2mif.R` pulls, add an issue for each failing summation and assign people to them.

**Comment by fbenke-pik** [comment]
> Commit these additional checks, 

I will do that, as soon as @fschreyer confirms that the summations as committed here are correct and the problem is indeed with the data/reporting

> update the gdxes test-convGDX2mif.R pulls

This has been done. I replaced the gdx pulled from RSE server as part of the test. No code change necessary.

> add an issue for each failing summation and assign people to them.

That would be sth. @fschreyer has to do, as I would not know the responsibilities,

**Review by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q — APPROVED** [review]

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
@fschreyer is not in today, so I set up #469, #470, #471, #472, #473.  They can be triaged and assigned when he is back.

**Pull request merged**
