### PR TITLE
Overhaul of emissions reporting

### PR DESCRIPTION
**Pull request by fschreyer**
Complete overhaul of emissions reporting. 

Please do not merge yet until all issues resolved.

### CODE REVIEW

**Review by giannou — CHANGES_REQUESTED** [review]
I get the following error with your code:
```
Error (test-convGDX2mif.R:89:5): Test if REMIND reporting is produced as it should and check data integrity
Error: invalid regular expression '^Emi\|GHG\|CO2Eq\|++\|ESR$', reason 'Invalid use of repetition operators'
Backtrace:
 1. remind2:::check_integrity(a) test-convGDX2mif.R:89:4
 2. mip::extractVariableGroups(unique(dt[["variable"]]), keepOrigNames = T) test-convGDX2mif.R:58:4
 3. mip:::tmp(matches, sep = sep, ext = ext, allVars = x, keepOrigNames) /home/giannou/GitHub/mip/R/extractVariableGroups.R:40:4
 4. base::grep(...) /home/giannou/GitHub/mip/R/extractVariableGroups.R:25:8
 ```
Didn't you get the same error?

**Comment by fschreyer** [comment]
Yes, I get the same error when building. However, I also tested running check_integrity() manually. So, there is another error down the line. I guess, the first problem is that it cannot cope with 2 ``++``, although that worked in reportFE, right? Another thing is that the aggregation seems to have an issue with detecting the correct variable to add up to when there are multiple pluses in one variable.

**Comment by fschreyer** [comment]
> 
> 
> Further, when testing if `compareScenarios` works, one gets the following error:
> 
> ```
> Error: subscript out of bounds ("Emi|CO2|Gross Fossil Fuels and Industry (Mt CO2/yr)")
> ```

Ah true. I forgot to touch compare scenarios so far Very important! I will follow up on that. If in the meantime, you could figure out this aggregation check issue, that would be great!

**Comment by giannou** [comment]
> If in the meantime, you could figure out this aggregation check issue, that would be great!

working on it right now :)

**Comment by giannou** [comment]
> > If in the meantime, you could figure out this aggregation check issue, that would be great!
> 
> working on it right now :)

@fschreyer the checks are working with this [PR](https://github.com/pik-piam/mip/pull/18). You might want to check why the following emissions groups don't add up: 
* Emi|CO2 (Mt CO2/yr)
* Emi|CO2|+|Energy (Mt CO2/yr)
* Emi|CO2|+|Process (Mt CO2/yr)
* Emi|GHG|CO2Eq (Mt CO2eq/yr)
 * Emi|Gross CO2 (Mt CO2/yr)
 * Emi|Gross CO2|+|Energy (Mt CO2/yr)

**Comment by giannou** [comment]
just a heads-up: don't merge just yet because the pluses in some variable names will have to change to correctly reflect the logic of the "aggregation per plus symbols" system

**Comment by fschreyer** [comment]
No worries! I will not merge this one without consent. There are still some steps to do and I will write an email to everyone before the merge as this might affect workflows of some people as well and give time to respond.

**Comment by fschreyer** [comment]
Ok, my tests are done so far. I checked all plus aggregations with different gdx's. Well, there are still some second-order emissions variables missing but, I guess, we will add them over the coming weeks. 

@giannou Could you update the test GDX to this one ``/p/tmp/schreyer/Modeling/REMIND_H12/Current/output/SSP2-PkBudg900_synf_2021-04-13_11.19.57``. It is a policy run I just made containing CDR and CCU. Emissions markets are not in there, because we have them only for REMIND-EU runs and we would not like to test against a 21 region gdx, I guess. I tested aggregations also with emission markets gdx. So should be fine for now.

**Comment by giannou** [comment]
Ok I updated the GDX

**Comment by giannou** [comment]
For the groups that don't add up (and make the R package tests fail): do we add them in a temporary ignore list and convert to 
(preferably annoying) warnings?

**Comment by fschreyer** [comment]
All groups should add up...in my tests they did. which ones dont?

**Comment by giannou** [comment]
> All groups should add up...in my tests they did. which ones dont?

For the sake of documentation (because the discussion has moved to a private channel due to the amount of messages), several groups don't add up and are fixed right now

**Review by giannou — APPROVED** [review]

**Comment by fschreyer** [comment]
@0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q 

I removed aggregate industry FE variables from the industry subsector reporting with [this commit](https://github.com/pik-piam/remind2/pull/29/commits/1da67f33b3fb18007c15346a9b51f65cc6810bb3) because after removing the pluses there are duplicates with the "+" FE variables which lead to some issues. Just to let you know.

**Comment by fschreyer** [comment]
@giannou 
I am ready to merge again. Let me know if you see remaining issues/tests to be completed. I tested all aggregations also for the new default gdx (I sent you on mattermost). Can you insert this new GDX as test GDX again once the library is merged?

**Comment by giannou** [comment]
Sure, I can do that.

**Pull request merged**
