### PR TITLE
updated reportEmployment() for remind2

### PR DESCRIPTION
**Pull request by amnmalik**
same commit as in remind  + changes to allow to read new gdxs

### CODE REVIEW

**Review by christophbertram — APPROVED** [review]
The commit looks good. The commit message so far omits the new parameters 'type' ( either "created" or "per_year". The former outputs jobs created in that year whereas the latter outputs total jobs in that year) and 'multiplier' (controls how the regional multiplier for non-oecd countries changes with time.), and the share parameter is actually called 'share_manf'.

**Comment by pfuehrlich-pik** [comment]
Can you please run `lucode2::buildLibrary()` to run the checks and increase the version number? @amnmalik

**Comment by amnmalik** [comment]
> The commit looks good. The commit message so far omits the new parameters 'type' ( either "created" or "per_year". The former outputs jobs created in that year whereas the latter outputs total jobs in that year) and 'multiplier' (controls how the regional multiplier for non-oecd countries changes with time.), and the share parameter is actually called 'share_manf'.

Thanks, Christoph. Yes, this was an initial commit. Future smaller commits and bugfixes will follow.

**Comment by amnmalik** [comment]
> 
> 
> Can you please run `lucode2::buildLibrary()` to run the checks and increase the version number? @amnmalik

I did run `lucode2::buildlibrary()` , that's why a new NAMESPACE was created. Don't know why the buildnumber didn't change.

**Comment by pfuehrlich-pik** [comment]
Maybe someone else pushed some another changes with the same version number. The version number was increased in the meantime, so you don't need to increase it again for this PR. Just make sure that the version number is increased in future PRs :slightly_smiling_face:

**Pull request merged**
