### PR TITLE
add test for ranges on convGDX2MIF() output

### LINKED ISSUE #526: Add structure for range checks
Should be possible to test stuff like `Emi|CO2|Energy|Demand|Industry|Chemicals|Solids|+|Fossil > 0`.

FYI @fbenke-pik.

### PR DESCRIPTION
**Pull request by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q**
close #526

### CODE REVIEW

**Review by pweigmann — APPROVED** [review]

**Review by fbenke-pik — APPROVED** [review]

**Comment by orichters** [comment]
Wouldn't it make sense to run this check every time `convGDX2MIF` is run, not only in the tests? If there is such an inconsistency in any run, it would be good to know…

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
That dawned on me over the weekend as well.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
I will hold this back anyhow, since the test would currently break `remind2` building (because `remind2` is broken).

**Comment by orichters** [comment]
Or, you could: turn `stop` into `warning`, accept that warning in `.buildLibrary`, and merge it, so people working on the issues can more easily keep track of these inconsistencies (and make sure we don't add some).

Of course, this implies that people would actually care about these test warnings. History shows they don't.

**Review by pweigmann — APPROVED** [review]
Definitely looks very similar to a special application case of the validation tool now, would be curious to see how performance compares. Support for regex variable selection is the only thing I can see right now that is not available in [``validateScenarios``](https://github.com/pik-piam/piamValidation/blob/main/R/validateScenarios.R).

**Pull request merged**
